[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[context.production]
  command = "bundle exec jekyll build --config _config.yml,_config.prod.yml"
  publish = "_site"

[context.deploy-preview]
  command = "bundle exec jekyll build --config _config.yml,_config.preview.yml"
  publish = "_site"

[context.branch-deploy]
  command = "bundle exec jekyll build --config _config.yml,_config.branch.yml"
  publish = "_site"
