[[plugins]]
  package = "netlify-plugin-jekyll-cache"

[[plugins]]
  package = "netlify-plugin-html-validate"

  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"

[[plugins]]
  package = "netlify-plugin-is-website-vulnerable"

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
  entryPoints = [
    "*.html",
  ]

  recursive = true
  pretty = true
  skipPatterns = []
  todoPatterns = []
  checkExternal = false
  followSourceMaps = false

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

  [[plugins.inputs.thresholds]]
    performance = 0.9

  [[plugins.inputs.audits]]
    path = "route1"
    output_path = "reports/route1.html"

  [[plugins.inputs.audits]]
    url = "https://bashlstore.netlify.app"
    [plugins.inputs.audits.thresholds]
      performance = 0.8
